"""Centralized HTML ID constants for plugin selector components"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/html_ids.ipynb.

# %% auto 0
__all__ = ['PluginSelectorHtmlIds']

# %% ../../nbs/components/html_ids.ipynb 3
class PluginSelectorHtmlIds:
    """HTML ID constants for plugin selector components."""
    
    # Main plugin selector container
    PLUGIN_SELECTOR = "plugin-selector"
    
    # Dropdown/select element
    PLUGIN_SELECT = "plugin-select"
    
    # Details section showing selected plugin info
    PLUGIN_DETAILS = "plugin-details"
    
    # Comparison table container
    PLUGIN_COMPARISON = "plugin-comparison"
    
    # Toggle button for showing/hiding comparison
    COMPARISON_TOGGLE = "comparison-toggle"
    
    @staticmethod
    def as_selector(
        id_str: str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"
